name: TODO Last-Updated
on:
  push:
    paths:
      - 'docs/TODO.md'
permissions:
  contents: write
jobs:
  update-todo-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update last-updated date
        run: |
          DATE=$(date +'%Y-%m-%d')
          sed -i "s/^\\*Last updated:.*$/\*Last updated: \`${DATE}\`*/" docs/TODO.md

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet docs/TODO.md; then
            git add docs/TODO.md
            git commit -m "chore(todo): auto-update TODO last-updated to ${DATE} 📅"
            git push
          else
            echo "No changes in docs/TODO.md — skipping commit."
          fi